services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpnservice_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - vpnservice_network
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "php-fpm", "-t" ]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx
    container_name: vpnservice_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - vpnservice_network
    depends_on:
      - app

  postgres:
    image: postgres:17
    container_name: vpnservice_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vpnservice
      POSTGRES_USER: vpnservice_user
      POSTGRES_PASSWORD: vpnservice_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - vpnservice_network

volumes:
  postgres_data:
    driver: local

networks:
  vpnservice_network:
    driver: bridge
